security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Nakupujem\ShopBundle\Entity\User: plaintext
        Nakupujem\ShopBundle\Entity\Shop: plaintext

    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_SHOP:       ROLE_SHOP
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        entity_user:
                entity: { class: NakupujemShopBundle:User, property: username }
        entity_shop:
                entity: { class: NakupujemShopBundle:Shop, property: email }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        demo_login:
            pattern:  ^/demo/secured/login$
            security: false

        demo_secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _demo_security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

        user_area:
            pattern:    /user/*
            provider: entity_user
            #anonymous: ~
            form_login:
                check_path: _user_security_check
                login_path: _user_login
                always_use_default_target_path: false
                default_target_path: /user/
            logout: 
                path:   _user_logout
                target: /   

        shop_area:
            pattern: ^/shop
            provider: entity_shop
            form_login:
                check_path: _shop_security_check
                login_path: _shop_login
                always_use_default_target_path: false
                default_target_path: /shop/
            logout:
                path: _shop_logout
                target: /

    access_control:
        user_login:
            path: /login/user
            roles: IS_AUTHENTICATED_ANONYMOUSLY
        user_area:
            path: ^/user/*
            roles: ROLE_USER
        shop_login:
            path: /ĺogin/shop
            roles: IS_AUTHENTICATED_ANONYMOUSLY
        shop_area:
            path: ^/shop/*
            roles: ROLE_SHOP
